spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5438/postgres
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false

  #  cron = "1 2 3 4 5 6"
  #  1: segundo (preenchido de 0 a 59)
  #  2: minuto (preenchido de 0 a 59)
  #  3 hora (preenchido de 0 a 23)
  #  4 dia (preenchido de 0 a 31)
  #  5 mês (preenchido de 1 a 12)
  #  6 dia da semana (preenchido de 0 a 6)

  scheduler:
    start: 10 * * * * *
    zone: America/Sao_Paulo